server:
  port: 8081
  servlet:
    context-path: /blog
constant:
  backendUrl: http://localhost:8080

---
# profiles value 할당 (방법1)
# java -jar 파일명.jar --spring.profiles.active=profiles값 (택1)
# java -Dspring.profiles.active=profiles값 -jar 파일명.jar (택2)
# profiles value 할당 (방법2)
# Edit Configurations > Run/Debug Configurations > Active Profiles 값 할당
# .\gradlew build -x test -Pprofile=prod
# 빌드시 테스트 진행하지 않고 prod 로 실행
---
spring:
  profiles:
    active: prod
server:
  port: 8080
  servlet:
    context-path: /
constant:
  backendUrl: http://shkim30.cafe24.com